services:
  backend:
    build:
      context: .
    volumes:
      - .:/code/
    working_dir: /code
    command: [ "python", "manage.py", "runserver", "0.0.0.0:5500" ]
    ports:
      - "5500:5500"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
  db:
    image: postgres:9.6-alpine
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: campaignerapi
      POSTGRES_USER: campaignerapi
      POSTGRES_PASSWORD: password
  celery_beat:
    build:
      context: .
    volumes:
      - .:/code/
    working_dir: /code
    command: celery -A campaignerapi beat -l DEBUG
    env_file:
      - .env
  celery_worker:
    build:
      context: .
    volumes:
      - .:/code/
    working_dir: /code
    command: celery -A campaignerapi worker -l DEBUG
    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3.8-management
volumes:
  db-data:
    driver: local
