apiVersion: v1
kind: Service
metadata:
  name: celery-beat
spec:
  selector:
    app: celery
    component: beat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000  # or the port you want to expose
