# Generated by Django 3.2.9 on 2023-03-20 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaignerapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='summary',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='messages',
            old_name='description',
            new_name='subject',
        ),
    ]
