# Generated by Django 3.2.9 on 2023-05-20 22:49

import campaignerapi.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campaignerapi', '0002_auto_20230320_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messages',
            name='sending_datetime',
            field=models.DateTimeField(null=True, validators=[campaignerapi.validators.date_is_present_or_future]),
        ),
        migrations.AddField(
            model_name='messages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
