apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
    - name: "5500"
      port: 5500
      targetPort: 5500
  selector:
    io.kompose.service: backend
