apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db/db-deployment.yaml
  - rabbitmq/rabbitmq-deployment.yaml
  - backend/backend-deployment.yaml
  - celery/celery-worker-deployment.yaml
  - celery/celery-beat-deployment.yaml